export const LOGIN_VIA_EMAIL = 'AUTH/LOGIN_VIA_EMAIL';
export const LOGIN_VIA_EMAIL_FULFILLED = 'AUTH/LOGIN_VIA_EMAIL_FULFILLED';
export const LOGIN_VIA_EMAIL_ERRORED = 'AUTH/LOGIN_VIA_EMAIL_ERRORED';

export const SIGNUP_VIA_EMAIL = 'AUTH/SIGNUP_VIA_EMAIL';
export const SIGNUP_VIA_EMAIL_ERRORED = 'AUTH/SIGNUP_VIA_EMAIL_ERRORED';
export const SIGNUP_VIA_EMAIL_FULFILLED = 'AUTH/SIGNUP_VIA_EMAIL_FULFILLED';
export const SIGNUP_VIA_EMAIL_CANCELLED = 'AUTH/SIGNUP_VIA_EMAIL_CANCELLED';

export const  REGISTER_FCM_TOKEN = 'AUTH/FCM/REGISTER_FCM_TOKEN';
export const  REGISTER_FCM_TOKEN_ERRORED = 'AUTH/FCM/REGISTER_FCM_TOKEN_ERRORED';
export const  REGISTER_FCM_TOKEN_FULFILLED = 'AUTH/FCM/REGISTER_FCM_TOKEN_FULFILLED';
