export const LOGIN_VIA_EMAIL = 'AUTH/LOGIN_VIA_EMAIL';
export const LOGIN_VIA_EMAIL_FULFILLED = 'AUTH/LOGIN_VIA_EMAIL_FULFILLED';
export const LOGIN_VIA_EMAIL_ERRORED = 'AUTH/LOGIN_VIA_EMAIL_ERRORED';

export const SIGNUP_VIA_EMAIL = 'AUTH/SIGNUP_VIA_EMAIL';
export const SIGNUP_VIA_EMAIL_ERRORED = 'AUTH/SIGNUP_VIA_EMAIL_ERRORED';
export const SIGNUP_VIA_EMAIL_FULFILLED = 'AUTH/SIGNUP_VIA_EMAIL_FULFILLED';
export const SIGNUP_VIA_EMAIL_CANCELLED = 'AUTH/SIGNUP_VIA_EMAIL_CANCELLED';

export const  REGISTER_FCM_TOKEN = 'FCM/REGISTER_FCM_TOKEN';
export const  REGISTER_FCM_TOKEN_ERRORED = 'FCM/REGISTER_FCM_TOKEN_ERRORED';
export const  REGISTER_FCM_TOKEN_FULFILLED = 'FCM/REGISTER_FCM_TOKEN_FULFILLED';
export const  REFRESH_FCM_TOKEN = 'FCM/REFRESH_FCM_TOKEN';
export const  REFRESH_FCM_TOKEN_FULFILLED = 'FCM/REFRESH_FCM_TOKEN_FULFILLED';
export const  REFRESH_FCM_TOKEN_ERRORED = 'FCM/REFRESH_FCM_TOKEN_ERRORED';

export const FETCH_ALL_PROJECTS = 'PROJECTS/FETCH_ALL_PROJECTS';
export const FETCH_ALL_PROJECTS_ERRORED = 'PROJECTS/FETCH_ALL_PROJECTS_ERRORED';
export const FETCH_ALL_PROJECTS_FULFILLED = 'PROJECTS/FETCH_ALL_PROJECTS_FULFILLED';
export const SET_SELECTED_PROJECT = 'SET_SELECTED_PROJECT';

export const DOWNLOAD_STARTED = 'DOWNLOAD/DOWNLOAD_STARTED';
export const DOWNLOAD_ERRORED = 'DOWNLOAD/DOWNLOAD_ERRORED';
export const DOWNLOAD_COMPLETED = 'DOWNLOAD/DOWNLOAD_COMPLETED';
export const UPDATE_CURRENT_DOWNLOAD_PROGRESS = 'DOWNLOAD/UPDATE_CURRENT_DOWNLOAD_PROGRESS';

export const INSTALL_APK = 'APK/INSTALL_APK';
export const INSTALL_APK_ERRORED = 'APK/INSTALL_APK_ERRORED';
export const INSTALL_APK_FULFILLED = 'APK/INSTALL_APK_FULFILLED';

